---
# Source: gateway/templates/istio-ingress.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-app-gateway
  namespace: istio-ingress
  labels:
    helm.sh/chart: gateway-1.16.0
    app: istio-app-gateway
    istio: istio-app-gateway
    #    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/name: istio-app-gateway
  annotations:
    {}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: istio-app-gateway
      istio: istio-app-gateway
  template:
    metadata:
      annotations:
        inject.istio.io/templates: gateway
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "15020"
        prometheus.io/scrape: "true"
        sidecar.istio.io/inject: "true"
      labels:
        sidecar.istio.io/inject: "true"
        app: istio-app-gateway
        istio: istio-app-gateway
    spec:
      serviceAccountName: istio-app-gateway
      securityContext:
        # Safe since 1.22: https://github.com/kubernetes/kubernetes/pull/103326
        sysctls:
          - name: net.ipv4.ip_unprivileged_port_start
            value: "0"
      containers:
        - name: istio-proxy
          # "auto" will be populated at runtime by the mutating webhook. See https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#customizing-injection
          image: auto
          securityContext:
            # Safe since 1.22: https://github.com/kubernetes/kubernetes/pull/103326
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsUser: 1337
            runAsGroup: 1337
            runAsNonRoot: true
          ports:
            - containerPort: 15090
              protocol: TCP
              name: http-envoy-prom
          resources:
            limits:
              cpu: 3000m
              memory: 1024Mi
            requests:
              cpu: 2000m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: istio-app-gateway-svc
  namespace: istio-ingress
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
    kubernetes.io/ingress.class: "gce-internal"
  labels:
    helm.sh/chart: gateway-1.16.0
    app: istio-app-gateway
    istio: istio-app-gateway
spec:
  type: LoadBalancer
  ports:
    - name: status-port
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
#    - name: https
#      port: 443
#      protocol: TCP
#      targetPort: 443
  selector:
    app: istio-app-gateway
    istio: istio-app-gateway
---
# Source: gateway/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: istio-app-gateway
  namespace: istio-ingress
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
---
# Source: gateway/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-app-gateway
  namespace: istio-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: istio-app-gateway
subjects:
  - kind: ServiceAccount
    name: istio-app-gateway
---
# Source: gateway/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: istio-app-gateway
  namespace: istio-ingress
  labels:
    app: istio-app-gateway
    istio: istio-app-gateway
  annotations:
    {}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istio-app-gateway
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 70
          type: Utilization
    - type: Resource
      resource:
        name: memory
        target:
          averageUtilization: 70
          type: Utilization
---
# Source: gateway/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-app-gateway
  namespace: istio-ingress
  labels:
    helm.sh/chart: gateway-1.16.0
    app: istio-app-gateway
    istio: istio-app-gateway
    #    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/name: istio-app-gateway



