apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    prometheus: prometheus
spec:
  replicas: 2
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  # additionalScrapeConfigs: |
  #   - job_name: "postgres"
  #     static_configs:
  #     - targets: ["postgres:8981"]
    
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml
