apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.project.app_name}}-service
  namespace: {{ .Values.project.namespace}}
  labels:
    app: {{ .Values.project.app_name}}
spec:
  selector:
    app: {{ .Values.project.app_name}}
    tier: {{ .Values.project.tier}}
  ports:
    - port: {{ .Values.project.service_port}}
      targetPort: {{ .Values.project.target_port}}
      protocol: TCP
      name: {{ .Values.project.app_name}}-service
