---
# Source: gateway/templates/istio-ingress.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-ingress-monitoring
  namespace: istio-ingress
  labels:
    helm.sh/chart: gateway-1.16.0
    app: istio-ingress-monitoring
    istio: istio-ingress-monitoring
    #    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/name: istio-ingress-monitoring
  annotations:
    {}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: istio-ingress-monitoring
      istio: istio-ingress-monitoring
  template:
    metadata:
      annotations:
        inject.istio.io/templates: gateway
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "15020"
        prometheus.io/scrape: "true"
        sidecar.istio.io/inject: "true"
      labels:
        sidecar.istio.io/inject: "true"
        app: istio-ingress-monitoring
        istio: istio-ingress-monitoring
    spec:
      serviceAccountName: istio-ingress-monitoring
      securityContext:
        # Safe since 1.22: https://github.com/kubernetes/kubernetes/pull/103326
        sysctls:
          - name: net.ipv4.ip_unprivileged_port_start
            value: "0"
      containers:
        - name: istio-proxy
          # "auto" will be populated at runtime by the mutating webhook. See https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#customizing-injection
          image: auto
          securityContext:
            # Safe since 1.22: https://github.com/kubernetes/kubernetes/pull/103326
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsUser: 1337
            runAsGroup: 1337
            runAsNonRoot: true
          ports:
            - containerPort: 15090
              protocol: TCP
              name: http-envoy-prom
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: istio-ingress-monitoring-svc
  namespace: istio-ingress
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
    kubernetes.io/ingress.class: "gce-internal"
  labels:
    helm.sh/chart: gateway-1.16.0
    app: istio-ingress-monitoring
    istio: istio-ingress-monitoring
spec:
  type: LoadBalancer
  ports:
    - name: monitoring-status-port
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: monitoring-http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: istio-ingress-monitoring
    istio: istio-ingress-monitoring
---
# Source: gateway/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: istio-ingress-monitoring
  namespace: istio-ingress
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
---
# Source: gateway/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-ingress-monitoring
  namespace: istio-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: istio-ingress-monitoring
subjects:
  - kind: ServiceAccount
    name: istio-ingress-monitoring
---
# Source: gateway/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: istio-ingress-monitoring
  namespace: istio-ingress
  labels:
    app: istio-ingress-monitoring
    istio: istio-ingress-monitoring
  annotations:
    {}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istio-ingress-monitoring
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 70
          type: Utilization
---
# Source: gateway/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-ingress-monitoring
  namespace: istio-ingress
  labels:
    helm.sh/chart: gateway-1.16.0
    app: istio-ingress-monitoring
    istio: istio-ingress-monitoring
    #    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/name: istio-ingress-monitoring



