project:
  redis:
    host:
    passowrd:
    port: 6379
    timeout: 60000
    max_pool_connection_size: 10
    min_idle_connection: 2
    postgres:
      config:
        master:
          url:
          username:
          password:
        slave:
          url:
          username:
          password:
      rbac:
        master:
          url:
          username:
          password:
        slave:
          url:
          username:
          password:
      analyzer:
        master:
          url:
          username:
          password:
        slave:
          url:
          username:
          password:
