project:
  image_pull_policy: Always
  image:
    registry:
  autoscaling:
    enabled: true
    default_replica: 3
    minReplicas: 1
    maxReplicas: 6
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 70
  java_heap_config: "-Xmx2048M -Xms1024M"
  resources:
    requests:
      memory: "16Mi"
      cpu: "50m"    # 500milliCPUs (1/2 CPU)
    limits:
      memory: "128Mi"
      cpu: "100m"
  services:
    config:
      name: config-service
    gateway:
      name: gateway-service
    rbac:
      name: rbac
    analyzer:
      name: analyzer-service
    kong:
      name: kong
      endpoint: