apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.project.default_configs}}
  namespace: {{ .Values.project.namespace}}
data:
  CONFIG_URL: "{{ .Values.project.services.config.name}}.{{ .Values.project.namespace}}.svc.cluster.local:{{ .Values.project.services.config.port}}"
  ANALYZER_URL: "{{ .Values.project.services.analyzer.name}}.{{ .Values.project.namespace}}.svc.cluster.local:{{ .Values.project.services.analyzer.port}}"
  RBAC_URL: "{{ .Values.project.services.rbac.name}}.{{ .Values.project.namespace}}.svc.cluster.local:{{ .Values.project.services.rbac.port}}"
  GATEWAY_URL: "{{ .Values.project.services.gateway.name}}.{{ .Values.project.namespace}}.svc.cluster.local:{{ .Values.project.services.gateway.port}}"
  KONG_ADMIN_HOST: {{ .Values.project.services.kong.endpoint}}
  BOOTSTRAP_SERVER: {{ .Values.project.kafka.bootstrap_servers}}
  TZ: {{ .Values.project.TZ}}
  REDIS_PORT: {{quote .Values.project.redis.port}}
  REDIS_TIMEOUT: {{quote .Values.project.redis.timeout}}
  REDIS_CONNECTION_MAXIMUM_POOL_SIZE: {{quote .Values.project.redis.max_pool_connection_size}}
  REDIS_CONNECTION_MINIMUM_IDLE: {{quote .Values.project.redis.min_idle_connection}}
  SERVER_PORT: {{quote .Values.project.image.containerPort}}
  JAVA_OPTS: {{ .Values.project.java_heap_config}}
  KAFKA_HEAP_OPTS: {{ .Values.project.java_heap_config}}
  JVM_ARGS: {{ .Values.project.java_heap_config}}