apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.project.default_secrets}}
  namespace: {{ .Values.project.namespace}}
data:
  CONFIG_MASTER_URL: {{ .Values.project.postgres.config.master.url}}
  CONFIG_MASTER_USERNAME: {{ .Values.project.postgres.config.master.username}}
  CONFIG_MASTER_PASS: {{ .Values.project.postgres.config.master.password}}
  CONFIG_SLAVE_URL: {{ .Values.project.postgres.config.slave.url}}
  CONFIG_SLAVE_USERNAME: {{ .Values.project.postgres.config.slave.username}}
  CONFIG_SLAVE_PASS: {{ .Values.project.postgres.config.slave.password}}
  ANALYSER_MASTER_URL: {{ .Values.project.postgres.analyzer.master.url}}
  ANALYSER_MASTER_USERNAME: {{ .Values.project.postgres.analyzer.master.username}}
  ANALYSER_MASTER_PASS: {{ .Values.project.postgres.analyzer.master.password}}
  ANALYSER_SLAVE_URL: {{ .Values.project.postgres.analyzer.slave.url}}
  ANALYSER_SLAVE_USERNAME: {{ .Values.project.postgres.analyzer.slave.username}}
  ANALYSER_SLAVE_PASS: {{ .Values.project.postgres.analyzer.slave.password}}
  RBAC_MASTER_URL: {{ .Values.project.postgres.rbac.master.url}}
  RBAC_MASTER_USERNAME: {{ .Values.project.postgres.rbac.master.username}}
  RBAC_MASTER_PASS: {{ .Values.project.postgres.rbac.master.password}}
  RBAC_SLAVE_URL: {{ .Values.project.postgres.rbac.slave.url}}
  RBAC_SLAVE_USERNAME: {{ .Values.project.postgres.rbac.slave.username}}
  RBAC_SLAVE_PASS: {{ .Values.project.postgres.rbac.slave.password}}
  REDIS_HOST: {{ .Values.project.redis.host}}
  REDIS_PASS: {{ .Values.project.redis.passowrd}}